<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CommunityPostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $community_posts = array(
            array('id' => '1','category_id' => '1','title' => 'Total station Operator 1','location' => 'Chennai, Arumbakkam','mobile' => '7865421541','description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:24:50','updated_at' => '2023-11-01 12:24:50'),
            array('id' => '2','category_id' => '2','title' => 'Assistant Surveyor 1','location' => 'Chennai, Tambaram','mobile' => '9658452154','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:30:31','updated_at' => '2023-11-01 12:30:31'),
            array('id' => '3','category_id' => '3','title' => 'Land Surveying 1','location' => 'Chennai, Trivotriyur','mobile' => '9854756215','description' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            array('id' => '4','category_id' => '4','title' => 'Machine Rent 1','location' => 'Thirumangalam, Ambattur','mobile' => '9854756215','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
           
            array('id' => '5','category_id' => '1','title' => 'Total station Operator 2','location' => 'Chennai, Thiruvanmiyur','mobile' => '7865421541','description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:24:50','updated_at' => '2023-11-01 12:24:50'),
            array('id' => '6','category_id' => '2','title' => 'Assistant Surveyor 2','location' => 'Chennai, Pallavandhangal','mobile' => '9658452154','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:30:31','updated_at' => '2023-11-01 12:30:31'),
            array('id' => '7','category_id' => '3','title' => 'Land Surveying 2','location' => 'Chennai, Koyambedu','mobile' => '9854756215','description' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            array('id' => '8','category_id' => '4','title' => 'Machine Rent 2','location' => 'Thirumangalam, Ambattur Estate','mobile' => '9854756215','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
           
            array('id' => '9','category_id' => '1','title' => 'Total station Operator 3','location' => 'Madurai, Annanagar','mobile' => '7865421541','description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:24:50','updated_at' => '2023-11-01 12:24:50'),
            array('id' => '10','category_id' => '2','title' => 'Assistant Surveyor 3','location' => 'Chennai, Viyasarpadi','mobile' => '9658452154','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:30:31','updated_at' => '2023-11-01 12:30:31'),
            array('id' => '11','category_id' => '3','title' => 'Land Surveying 3','location' => 'Chennai, Trivotriyur','mobile' => '9854756215','description' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            array('id' => '12','category_id' => '4','title' => 'Machine Rent 3','location' => 'Thirumangalam, Periyarnagar','mobile' => '9854756215','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            
            array('id' => '13','category_id' => '1','title' => 'Total station Operator 4','location' => 'Chennai, Mylapore','mobile' => '7865421541','description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:24:50','updated_at' => '2023-11-01 12:24:50'),
            array('id' => '14','category_id' => '2','title' => 'Assistant Surveyor 4','location' => 'Chennai, Saidhapet','mobile' => '9658452154','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:30:31','updated_at' => '2023-11-01 12:30:31'),
            array('id' => '15','category_id' => '3','title' => 'Land Surveying 4','location' => 'Chennai, Korugupettai','mobile' => '9854756215','description' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            array('id' => '16','category_id' => '4','title' => 'Machine Rent 4','location' => 'Annasalai, Chennai','mobile' => '9854756215','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            
            array('id' => '17','category_id' => '1','title' => 'Total station Operator 5','location' => 'Chennai, Velacherry','mobile' => '7865421541','description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:24:50','updated_at' => '2023-11-01 12:24:50'),
            array('id' => '18','category_id' => '2','title' => 'Assistant Surveyor 5','location' => 'Chennai, Mundakaniamman Kovil','mobile' => '9658452154','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:30:31','updated_at' => '2023-11-01 12:30:31'),
            array('id' => '19','category_id' => '3','title' => 'Land Surveying 5','location' => 'Chennai, Chennai Fort','mobile' => '9854756215','description' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            array('id' => '20','category_id' => '4','title' => 'Machine Rent 5','location' => 'Thirumangalam, Chennai Beach','mobile' => '9854756215','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
           
            array('id' => '21','category_id' => '1','title' => 'Total station Operator 6','location' => 'Chennai, Chrompet','mobile' => '7865421541','description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:24:50','updated_at' => '2023-11-01 12:24:50'),
            array('id' => '22','category_id' => '2','title' => 'Assistant Surveyor 6','location' => 'Chennai, Tirisulam','mobile' => '9658452154','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:30:31','updated_at' => '2023-11-01 12:30:31'),
            array('id' => '23','category_id' => '3','title' => 'Land Surveying 6','location' => 'Chennai, St.Thomas mount','mobile' => '9854756215','description' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55'),
            array('id' => '24','category_id' => '4','title' => 'Machine Rent 6','location' => 'Chennai, OMR','mobile' => '9854756215','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.','image' => NULL,'status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2023-11-01 12:31:55','updated_at' => '2023-11-01 12:31:55')
          );
            DB::table('community_posts')->insert($community_posts);
    }
}
